<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="171426" started-at="2020-11-08T13:02:26Z" finished-at="2020-11-08T13:05:18Z">
    <groups>
    </groups>
    <test name="ComprePriceTest" duration-ms="38058" started-at="2020-11-08T13:02:26Z" finished-at="2020-11-08T13:03:04Z">
      <class name="com.zestmoney.compare.ComparePriceTest">
        <test-method status="PASS" signature="browser()[pri:0, instance:com.zestmoney.compare.ComparePriceTest@5f2108b5]" name="browser" is-config="true" duration-ms="6279" started-at="2020-11-08T13:02:26Z" finished-at="2020-11-08T13:02:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser -->
        <test-method status="FAIL" signature="getPriceAmazon()[pri:1, instance:com.zestmoney.compare.ComparePriceTest@5f2108b5]" name="getPriceAmazon" duration-ms="17460" started-at="2020-11-08T13:02:33Z" finished-at="2020-11-08T13:02:50Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
at com.zestmoney.compare.ComparePriceTest.getPriceAmazon(ComparePriceTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPriceAmazon -->
        <test-method status="PASS" signature="getPriceFlipKart()[pri:2, instance:com.zestmoney.compare.ComparePriceTest@5f2108b5]" name="getPriceFlipKart" duration-ms="14118" started-at="2020-11-08T13:02:50Z" finished-at="2020-11-08T13:03:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPriceFlipKart -->
        <test-method status="PASS" signature="compare()[pri:3, instance:com.zestmoney.compare.ComparePriceTest@5f2108b5]" name="compare" duration-ms="3" started-at="2020-11-08T13:03:04Z" finished-at="2020-11-08T13:03:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- compare -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.zestmoney.compare.ComparePriceTest@5f2108b5]" name="tearDown" is-config="true" duration-ms="130" started-at="2020-11-08T13:03:04Z" finished-at="2020-11-08T13:03:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.zestmoney.compare.ComparePriceTest -->
    </test> <!-- ComprePriceTest -->
    <test name="FacebookPostTest" duration-ms="133336" started-at="2020-11-08T13:03:04Z" finished-at="2020-11-08T13:05:18Z">
      <class name="com.zestmoney.facebook.FacebookTest">
        <test-method status="PASS" signature="browser()[pri:0, instance:com.zestmoney.facebook.FacebookTest@60c6f5b]" name="browser" is-config="true" duration-ms="4282" started-at="2020-11-08T13:03:04Z" finished-at="2020-11-08T13:03:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser -->
        <test-method status="PASS" signature="facebookLogin()[pri:1, instance:com.zestmoney.facebook.FacebookTest@60c6f5b]" name="facebookLogin" duration-ms="8810" started-at="2020-11-08T13:03:09Z" finished-at="2020-11-08T13:03:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebookLogin -->
        <test-method status="FAIL" signature="facebookPost()[pri:2, instance:com.zestmoney.facebook.FacebookTest@60c6f5b]" name="facebookPost" duration-ms="120119" started-at="2020-11-08T13:03:17Z" finished-at="2020-11-08T13:05:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed in facebook expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed in facebook expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.zestmoney.facebook.FacebookTest.facebookPost(FacebookTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebookPost -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.zestmoney.facebook.FacebookTest@60c6f5b]" name="tearDown" is-config="true" duration-ms="112" started-at="2020-11-08T13:05:18Z" finished-at="2020-11-08T13:05:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.zestmoney.facebook.FacebookTest -->
    </test> <!-- FacebookPostTest -->
  </suite> <!-- Suite -->
</testng-results>
